version: "3.8"

services:
  minecraft:
    # cmd: docker-compose exec minecraft rcon-cli
    image: itzg/minecraft-server
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      VERSION: "1.18.2"
      SERVER_NAME: "Not This Shit"
      MOTD: "Ah shit, here we go again"
      # MAX_BUILD_HEIGHT: 256
      VIEW_DISTANCE: 20
      # SIMULATION_DISTANCE: 5
      MAX_PLAYERS: 20
      # MAX_WORLD_SIZE: 10000
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "TRUE"
      FORCE_GAMEMODE: "TRUE"
      SPAWN_PROTECTION: 0

      # https://github.com/itzg/docker-minecraft-server#whitelist-players=
      # WHITELIST_FILE: /extra/whitelist.json
      ENABLE_WHITELIST: "TRUE"
      ENFORCE_WHITELIST: "TRUE"

      OPS: Huskydog9988
      OVERRIDE_OPS: "TRUE"

      ICON: https://i.kym-cdn.com/entries/icons/mobile/000/029/223/cover2.jpg
      OVERRIDE_ICON: "TRUE"

      SPIGET_RESOURCES: 81534
      MODS_FILE: /extras/plugins.txt
      REMOVE_OLD_MODS: "TRUE"

      DATAPACKS: /datapacks
      REMOVE_OLD_DATAPACKS: "TRUE"
      # resource pack for Incendium
      # RESOURCE_PACK: https://www.planetminecraft.com/data-pack/incendium-nether-expansion/download/file/15458331/

      MAX_MEMORY: 6G
      TZ: America/New_York
      ENABLE_ROLLING_LOGS: "TRUE"
      USE_AIKAR_FLAGS: "TRUE"
      VANILLATWEAKS_SHARECODE: p70HvM
      COPY_CONFIG_DEST: /data

      TYPE: PAPER
      EULA: "TRUE"
      SYNC_SKIP_NEWER_IN_DESTINATION: "FALSE"
    ports:
      # Java
      - "25565:25565"
      # Voice Chat
      - "24454:24454/udp"
    volumes:
      # main volume for mc data
      - "mcdata:/data"
      # extras
      - "./extras:/extras"
      # config
      - "./config:/config"
      # datapacks
      - "./datapacks:/datapacks"
    networks:
      - web

  backups:
    image: itzg/mc-backup
    restart: always
    environment:
      BACKUP_INTERVAL: "6h"
      PAUSE_IF_NO_PLAYERS: "FALSE"
      PRUNE_BACKUPS_DAYS: "7"
    volumes:
      # mount the same volume used by server, but read-only
      - mcdata:/data:ro
      # use a host attached directory so that it in turn can be backed up
      # to external/cloud storage
      - ./mc-backups:/backups
      # share network namespace with server to simplify rcon access
    network_mode: "service:minecraft"
    depends_on:
      - minecraft

volumes:
  mcdata:

networks:
  web:
    external: true
    name: web
