version: "3.8"

services:
  minecraft:
    # cmd: docker-compose exec minecraft rcon-cli
    image: itzg/minecraft-server
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      VERSION: "1.19.3"
      SERVER_NAME: "Not This Shit"
      MOTD: "Ah shit, here we go again"
      # MAX_BUILD_HEIGHT: 256
      VIEW_DISTANCE: 16
      SIMULATION_DISTANCE: 6
      MAX_PLAYERS: 69
      # MAX_WORLD_SIZE: 10000
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "TRUE"
      FORCE_GAMEMODE: "TRUE"
      SPAWN_PROTECTION: 0

      # https://github.com/itzg/docker-minecraft-server#whitelist-players=
      # WHITELIST_FILE: /extra/whitelist.json
      ENABLE_WHITELIST: "TRUE"
      ENFORCE_WHITELIST: "TRUE"

      WHITELIST: "MeerBiene2,mar1juhanna,Huskydog9988"
      DIFFICULTY: hard

      ONLINE_MODE: "TRUE"

      OPS: "Huskydog9988,MeerBiene2"
      OVERRIDE_OPS: "TRUE"

      ICON: https://i.kym-cdn.com/entries/icons/mobile/000/029/223/cover2.jpg
      OVERRIDE_ICON: "TRUE"

      # 247 = dynmap
      # 8631 = coreprotect
      SPIGET_RESOURCES: 81534,60623,27448,19254
      MODS_FILE: /extras/plugins.txt
      REMOVE_OLD_MODS: "TRUE"

      DATAPACKS: /datapacks
      REMOVE_OLD_DATAPACKS: "TRUE"
      # resource pack for Incendium
      # RESOURCE_PACK: https://www.planetminecraft.com/data-pack/incendium-nether-expansion/download/file/15458331/
      REMOVE_OLD_MODS_EXCLUDE: "sound-physics-remastered"

      MEMORY: 3G
      MAX_MEMORY: 6G

      EXEC_DIRECTLY: true
      USE_SIMD_FLAGS: true
      # https://github.com/etil2jz/etil-minecraft-flags
      JVM_OPTS: "-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:-UseBiasedLocking -XX:UseAVX=3 -XX:+UseStringDeduplication -XX:+UseFastUnorderedTimeStamps -XX:+UseAES -XX:+UseAESIntrinsics -XX:UseSSE=4 -XX:+UseFMA -XX:AllocatePrefetchStyle=1 -XX:+UseLoopPredicate -XX:+RangeCheckElimination -XX:+EliminateLocks -XX:+DoEscapeAnalysis -XX:+UseCodeCacheFlushing -XX:+SegmentedCodeCache -XX:+UseFastJNIAccessors -XX:+OptimizeStringConcat -XX:+UseCompressedOops -XX:+UseThreadPriorities -XX:+OmitStackTraceInFastThrow -XX:+TrustFinalNonStaticFields -XX:ThreadPriorityPolicy=1 -XX:+UseInlineCaches -XX:+RewriteBytecodes -XX:+RewriteFrequentPairs -XX:+UseNUMA -XX:-DontCompileHugeMethods -XX:+UseFPUForSpilling -XX:+UseFastStosb -XX:+UseNewLongLShift -XX:+UseVectorCmov -XX:+UseXMMForArrayCopy -XX:+UseXmmI2D -XX:+UseXmmI2F -XX:+UseXmmLoadAndClearUpper -XX:+UseXmmRegToRegMoveAll -Dfile.encoding=UTF-8 -Xlog:async -Djava.security.egd=file:/dev/urandom --add-modules=jdk.incubator.vector"
      TZ: America/New_York
      ENABLE_ROLLING_LOGS: "TRUE"
      USE_AIKAR_FLAGS: "TRUE"
      VANILLATWEAKS_SHARECODE: p70HvM
      COPY_CONFIG_DEST: /data

      # enable env variable replacement
      REPLACE_ENV_VARIABLES: "TRUE"
      REPLACE_ENV_DURING_SYNC: "TRUE"
      # define an optional prefix for your env variables you want to replace
      ENV_VARIABLE_PREFIX: "CFG_"
      # and here are the actual variables
      CFG_DB_HOST: "db"
      CFG_DB_PORT: "3306"
      CFG_DB_NAME: "dynmap"
      CFG_DB_USER: "dynmap"

      # found in env file
      # CFG_DB_PASSWORD: ""


      MODRINTH_PROJECTS: sound-physics-remastered,coreprotect

      # TYPE: PAPER
      # lets try pufferfish - nope only works till 1.18.2
      # TYPE: PUFFERFISH
      # lets try purpur - https://purpurmc.org/
      # nope paper better
      TYPE: PAPER
      EULA: "TRUE"
      SYNC_SKIP_NEWER_IN_DESTINATION: "FALSE"

      # enforce-secure-profile
      ENFORECE-SECURE-PROFILE: "FALSE"
    ports:
      # Java
      - "25565:25565"
      # Voice Chat
      - "24454:24454/udp"
      # dynmap
      - "8123:8123"
      # bedrock
      - "19132:19132/udp"
    volumes:
      # main volume for mc data
      - "./mc-data:/data"
      # extras
      - "./extras:/extras"
      # config
      - "./config:/config"
      # datapacks
      - "./datapacks:/datapacks"
      - "./data:/data"
    networks:
      - web
      - database
    depends_on:
      - db
    env_file:
      - .mariadb.env
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.minecraft.entrypoints=https"
      - "traefik.http.routers.minecraft.tls=true"
      - "traefik.http.routers.minecraft.tls.certresolver=le"

      - "traefik.http.routers.minecraft.rule=Host(`dynmap.kim.stlf.me`)"
      - "traefik.http.services.minecraft.loadbalancer.server.port=8123"

      - "traefik.docker.network=web"
      # - "traefik.port=8080"
      # - "traefik.protocol=http"

  backups:
    image: itzg/mc-backup
    restart: always
    environment:
      BACKUP_INTERVAL: "8h"
      PAUSE_IF_NO_PLAYERS: "FALSE"
      PRUNE_BACKUPS_DAYS: "7"
    volumes:
      # mount the same volume used by server, but read-only
      - ./mc-data:/data:ro
      # use a host attached directory so that it in turn can be backed up
      # to external/cloud storage
      - ./mc-backups:/backups
      # share network namespace with server to simplify rcon access
    network_mode: "service:minecraft"
    depends_on:
      - minecraft

  db:
    image: mariadb:10
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: dynmap
      MARIADB_USER: dynmap
      MARIADB_PASSWORD: example
      MARIADB_AUTO_UPGRADE: "TRUE"
    volumes:
      - mariadata:/var/lib/mysql
    env_file:
      - .mariadb.env
    networks:
      - database

volumes:
  mcdata:
  mariadata:


networks:
  database:
  web:
    external: true
    name: web
